### ISSUE TITLE
As a user, I want to publish my DR collection as a datalad collection 

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/dr-tools#3]

**Comment by hurngchunlee** [comment]
@robertoostenveld has developed a script to build public DSCs available on https://public.data.doonders.ru.nl into datalad datasets.

See https://github.com/Donders-Institute-Data

**Comment by hurngchunlee** [comment]
@robertoostenveld the repositoy https://github.com/Donders-Institute-Data is nicely organized.  Could you share the script?

**Comment by robertoostenveld** [comment]
Yes, I can share. At the moment it is a (small) collection of scripts of which the dependencies are not documented. I'll look into cleaning them up and document it. If someone is explicitly interested, I will give this more priority.

**Comment by robertoostenveld** [comment]
I have added the script that I (more or less) used to the https://github.com/Donders-Institute-Data/donders-institute-data/blob/main/README.md, which is the README for the meta collection. 

The script uses `download-url`, which turns out to be too slow for large collections (as it downloads every file). I am working on one particular collection right now, and that is already downloading and adding file-for-file since half December. Better would probably be to use `addurls`.

**Comment by robertoostenveld** [comment]
this can be closed if you want
